# Site settings
title: IGS'19
email: a.mahdavi.amiri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The International Geometry Summit 2019 (IGS2019) is a joint event and co-location of the major conferences in applied geometry.
baseurl: "/event-jekyll-theme"
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
